import { useState } from 'react'
import { FileSearch } from 'lucide-react'
import Header from './components/Header'
import PropertyForm from './components/PropertyForm'
import PredictionCard from './components/PredictionCard'
import LoadingState from './components/LoadingState'
import ErrorMessage from './components/ErrorMessage'
import { predictHousePrice, PredictionApiError } from './services/predictionApi'
import { toFeatureArray, type PredictionState, type PropertyDetails } from './types/prediction'

export default function App() {
  const [state, setState] = useState<PredictionState>({ status: 'idle' })
  const [lastSubmission, setLastSubmission] = useState<PropertyDetails | null>(null)

  async function runPrediction(details: PropertyDetails) {
    setLastSubmission(details)
    setState({ status: 'loading' })

    try {
      // Build the ordered feature array exactly as the model expects it.
      // { features: [[OverallQual, GrLivArea, GarageCars, TotalBsmtSF, FullBath, YearBuilt]] }
      const features = [toFeatureArray(details)]
      const value = await predictHousePrice(features)
      setState({ status: 'success', value })
    } catch (err) {
      const message =
        err instanceof PredictionApiError
          ? err.message
          : 'Something went wrong while generating your estimate.'
      setState({ status: 'error', message })
    }
  }

  function handleRetry() {
    if (lastSubmission) {
      runPrediction(lastSubmission)
    }
  }

  function handleReset() {
    setState({ status: 'idle' })
  }

  return (
    <div className="min-h-screen">
      <Header />

      <main className="mx-auto max-w-6xl px-6 py-10 sm:px-10 sm:py-14">
        <div className="mb-10 max-w-2xl">
          <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-appraisal-600">
            Instant estimate
          </p>
          <h1 className="mt-2 font-display text-3xl font-medium tracking-tight text-ink sm:text-4xl">
            What's your house actually worth?
          </h1>
          <p className="mt-3 text-ink-soft">
            Enter six property details and get an instant, data-driven price estimate —
            no agent, no guesswork.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2 lg:gap-8">
          <PropertyForm onSubmit={runPrediction} isSubmitting={state.status === 'loading'} />

          <div className="min-h-[420px]">
            {state.status === 'idle' && <IdleState />}
            {state.status === 'loading' && <LoadingState />}
            {state.status === 'error' && (
              <ErrorMessage message={state.message} onRetry={handleRetry} />
            )}
            {state.status === 'success' && (
              <PredictionCard value={state.value} onReset={handleReset} />
            )}
          </div>
        </div>
      </main>

      <footer className="mx-auto max-w-6xl px-6 py-8 sm:px-10">
        <p className="font-mono text-[11px] text-ink-soft">
          HomeValue AI estimates are generated by a machine learning model and are not a
          substitute for a professional appraisal.
        </p>
      </footer>
    </div>
  )
}

function IdleState() {
  return (
    <div className="flex h-full flex-col items-center justify-center rounded-2xl border border-dashed border-line-strong bg-white/40 p-10 text-center">
      <span className="flex h-11 w-11 items-center justify-center rounded-full bg-appraisal-50 text-appraisal-600">
        <FileSearch className="h-5 w-5" strokeWidth={2} />
      </span>
      <p className="mt-4 font-display text-lg text-ink">Your estimate will appear here</p>
      <p className="mt-1 max-w-xs text-sm text-ink-soft">
        Fill in the property details and select "Estimate House Price" to get started.
      </p>
    </div>
  )
}



